version: '3'
services:
  postgres:
    image: postgres:13
    container_name: homeworks-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5440}:5432
